Feature/footer
ITeam-by-GOIT/filmoteka pull request #6
Opened 2021-07-25 13:06 UTC by DukaDima

Сердечко сделал пнгшкой. Пока что... И без переменных, пока что.

2021-07-25 14:24 UTC, AngieBoiko commented on src/images/heard.svg
> +<svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
потом можно будет взять со спрайта, когда сольют в мейн

2021-07-25 14:24 UTC, AngieBoiko commented on src/partials/footer.html
> +<p class="footer-year"><span class="footer-copyright">©</span> 2020 </p>
можно добавить через спецсимвол https://www.toptal.com/designers/htmlarrows/symbols/copyright-sign/

2021-07-25 14:24 UTC, AngieBoiko commented on src/sass/layout/_footer.scss
> +  .container {
это уже прописано в отдельном файле со стилями контейнера

2021-07-25 14:24 UTC, AngieBoiko commented on src/sass/layout/_footer.scss
> +  .container {
это уже прописано в отдельном файле со стилями контейнера

2021-07-25 14:24 UTC, AngieBoiko commented on src/sass/layout/_footer.scss
> +  .container {
это уже прописано в отдельном файле со стилями контейнера

2021-07-25 14:26 UTC, Koliadjun requested changes
- [x] JPG лишні! в гілці main.
- [x] Prettier?
- [x] переглять стилі мені здається є декілька лишніх
- [x] пройдись по коментарях. Треба все уточнити

2021-07-25 14:26 UTC, ghost commented on src/sass/layout/_footer.scss
> +  font-family: Roboto;
є в body

2021-07-25 14:26 UTC, ghost commented on src/sass/layout/_footer.scss
> +  font-style: normal;
є в body

2021-07-25 14:26 UTC, ghost commented on src/sass/layout/_footer.scss
> +  font-weight: normal;
краще використовувати числовий вираз?!

2021-07-25 14:26 UTC, ghost commented on src/sass/layout/_footer.scss
> +  // background-color: rgb(202, 202, 247);
якщо не потрібно то видаляй

2021-07-25 14:26 UTC, ghost commented on src/partials/footer.html
> +        <!-- <svg class="footer-icon">
чому не svg? чекаєш на спрайт?

2021-07-25 14:26 UTC, ghost commented on src/partials/footer.html
> +        <p class="">by</p>
class не пиши якщо не потрібно

2021-07-25 14:26 UTC, ghost commented on src/sass/layout/_footer.scss
> +  .container {
так робити не варто так як потім ти комусь поламаєш верстку. Якщо контейнер не правильний то поправ контейнер у файлі контейнеру. Якщо є необхідність змінити у футері то роби окремий клас

2021-07-25 14:26 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  .footer-about-information {
На мою думку краще перенести це поза медіа правило і поставити в в клас без медіа правила [http://joxi.ru/Dr85Vl1IJM5B0m](url)
[http://joxi.ru/KAg4jy0iNKalLr](url)

2021-07-25 14:26 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  .container {
те саме

2021-07-25 14:26 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  .container {
те саме

2021-07-25 14:26 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  color: rgb(116, 5, 27);
давай тоді все в hex ну або поправим коли буде палітра

2021-07-25 14:26 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  left: 190px;
виглядає як хард код. А якщо буде більше тексту буде працювати?

2021-07-25 14:31 UTC, DukaDima commented on src/partials/footer.html
> +        <!-- <svg class="footer-icon">
Так

2021-07-25 14:32 UTC, DukaDima commented on src/sass/layout/_footer.scss
> +  color: rgb(116, 5, 27);
Да, цвета я пока прописал "примерно". Будут же переменные

2021-07-25 14:33 UTC, DukaDima commented on src/sass/layout/_footer.scss
> +  left: 190px;
В домашках так же дедали. Он же привязывается к левому верхнему углу относительного контейнера.

2021-07-25 15:54 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  left: 190px;
спробуй напиши більше тексту

2021-07-25 16:06 UTC, Koliadjun commented on src/partials/footer.html
> +<p class="footer-year"><span class="footer-copyright">©</span> 2020 </p>
Діма твоя думка?

2021-07-25 16:09 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  .container {
виправлено [https://github.com/ITeam-by-GOIT/filmoteka/pull/6/commits/63b6c9b5bb5de829fdcaf809fc707657cb31248b](url)

2021-07-25 16:09 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  .container {
виправлено [https://github.com/ITeam-by-GOIT/filmoteka/pull/6/commits/63b6c9b5bb5de829fdcaf809fc707657cb31248b](url)

2021-07-25 16:09 UTC, Koliadjun commented on src/sass/layout/_footer.scss
> +  .container {
виправлено [https://github.com/ITeam-by-GOIT/filmoteka/pull/6/commits/63b6c9b5bb5de829fdcaf809fc707657cb31248b](url)

2021-07-25 20:25 UTC, Koliadjun approved these changes
молодець

2021-07-25 20:27 UTC, Koliadjun approved these changes

2021-07-26 06:42 UTC, AngieBoiko reviewed
в стилях футера все еще есть размеры контейнера в медиа правиле  , дублируется @media screen and (min-width: 768px)

2021-07-26 07:41 UTC, Koliadjun commented
> в стилях футера все еще есть размеры контейнера в медиа правиле , дублируется в @media screen and (min-width: 768px)

поправив [https://github.com/ITeam-by-GOIT/filmoteka/pull/6/commits/e0117bb8064f1049980bc9a7a22de60d2455e4ff](url)

2021-07-26 07:44 UTC, AngieBoiko approved these changes

2021-07-26 07:44 UTC, merged